### ISSUE TITLE
Can't leave settings and return to home page

### ISSUE THREAD

**Issue by avinmaster** [DBChoco/Muezzin#42]
OS Version: Ubuntu 22.04.3 LTS.

**Comment by DBChoco** [comment]
Wa Alaykoum Assalam wa Rahmatou Lahi wa Baraketu.

Does it happen everytime ?
Can you try to play with the developper tools and tell me what you see ? Crtl + shift + i

Baraka Lahu feek.

**Comment by billynugrahas** [comment]
Hi @DBChoco , I'm also facing the same issue, I'm using Ubuntu 22.04 LTS.
Here is my console:
```
settings.html:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: file:///opt/muezzin/resources/app.asar/ressources/fonts/Quicksand-VariableFont_wght.ttf
settings.html:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: file:///opt/muezzin/resources/app.asar/ressources/fonts/weather-icons/font/weathericons-regular-webfont.woff2
settings.js:946 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'show')
    at loadQuranSettings (settings.js:946:50)
    at async loadSettings (settings.js:167:3)
settings.js:1019 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'trans')
    at settings.js:1019:47
settings.js:999 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'lang')
    at loadDefaultLang (settings.js:999:50)
    at settings.js:970:7
settings.html:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: file:///opt/muezzin/resources/app.asar/ressources/fonts/Quicksand-VariableFont_wght.ttf
settings.js:1104 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'value')
    at saveQuran (settings.js:1104:124)
    at async saveSettings (settings.js:73:3)
    at async set.onclick (settings.js:210:5)
saveQuran @ settings.js:1104
settings.js:1104 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'value')
    at saveQuran (settings.js:1104:124)
    at async saveSettings (settings.js:73:3)
    at async set.onclick (settings.js:210:5)
saveQuran @ settings.js:1104
settings.js:1104 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'value')
    at saveQuran (settings.js:1104:124)
    at async saveSettings (settings.js:73:3)
    at async set.onclick (settings.js:210:5)
saveQuran @ settings.js:1104
settings.js:1104 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'value')
    at saveQuran (settings.js:1104:124)
    at async saveSettings (settings.js:73:3)
    at async set.onclick (settings.js:210:5)
saveQuran @ settings.js:1104
```

Everytime I clicked Return, it throws this error: 
```
settings.js:1104 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'value')
    at saveQuran (settings.js:1104:124)
    at async saveSettings (settings.js:73:3)
    at async set.onclick (settings.js:210:5)
saveQuran @ settings.js:1104
```
